#!/usr/bin/env bash

# Путь к папке со скриптами
SCRIPTS_DIR="./deploy/scripts"

# Функция для вывода названий скриптов в папке
list_scripts() {
    local counter=0
    local script
    echo "Список скриптов в папке:"

    scripts_list=$(find "$SCRIPTS_DIR" -maxdepth 1 -type f)

    for script in $scripts_list; do
        counter=$(expr $counter + 1)
        echo "($counter) $(basename "$script")"
    done

    result=$counter
}


# Функция выбора по номеру
selectScript() {
    local script_counter="$1"
    local script_number
    # Запрашиваем у пользователя ввод номера скрипта
    echo "Введите номер скрипта (от 1 до $script_counter):"
    read script_number

    # Проверка ввода на корректность
    if [[ "$script_number" -lt 1 ]] || [[ "$script_number" -gt "$script_counter" ]]; then
        echo "Ошибка: введите правильный номер скрипта." >&2
        exit 1 # Используем return вместо exit, чтобы не завершать скрипт
    fi

    # Возвращаем имя скрипта под этим номером
    result=$(echo "$scripts_list" | sed -n "${script_number}p")
}


execScript() {
    # Получаем полный путь к скрипту, и проверяем его существование
    local selected_script="$1"
    local script_name=$(basename "$selected_script")
    # Запрос подтверждения перед выполнением
    echo "Вы уверены, что хотите запустить скрипт $script_name? (y/n)"
    read confirm
    if [ "$confirm" == "y" ]; then
        bash "$selected_script"
    else
        echo "Выполнение отменено."
        exit 0
    fi
}

# Вывод синтаксиса команды при наличии аргумента --help
if [ "$1" == "--help" ]; then
    echo "Синтаксис команды:"
    echo "  Без аргументов: запуск интерактивного режима выбора скрипта из папки."
    echo "  С аргументом: запуск выполнения указанного скрипта из папки."
    exit 0
fi

# Проверка наличия аргумента
if [ $# -eq 0 ]; then

    # Если скрипт вызван без аргументов, покажем ему все скрипты
    list_scripts
    script_counter=$result

    selectScript $script_counter
    selected_script=$result

    execScript $selected_script

elif [ $# -eq 1 ]; then
    # Если скрипт вызван с аргументом, проверяем его существование
    script_name="$1"
    # Ищем скрипт по имени в папке SCRIPTS_DIR
    selected_script=$(find "$SCRIPTS_DIR" -maxdepth 1 -type f -name "$script_name")

    if [ -z "$selected_script" ]; then
        echo "Скрипт $script_name не найден."
        exit 1
    fi
    execScript $selected_script

else
    echo "Неверное количество аргументов."
    exit 1
fi
