#!/usr/bin/env bash

# Путь к папке со скриптами
SCRIPTS_DIR="./deploy/scripts"

# Функция для вывода названий скриптов в папке
list_scripts() {
    local counter=1
    local script
    echo "Список скриптов в папке:"
    for script in "$SCRIPTS_DIR"/*; do
        if [ -f "$script" ]; then
            echo "($counter) $(basename "$script")"
            counter=$(expr $counter + 1)
        fi
    done
}


# Функция выбора по номеру
selectScript() {
    
    # Проверка ввода на корректность
    if [[ "$script_number" -lt 1 ]] || [[ "$script_number" -gt "$script_count" ]]; then
        echo "Ошибка: введите правильный номер скрипта." >&2
        exit 1 # Используем return вместо exit, чтобы не завершать скрипт
    fi

    # Возвращаем имя скрипта под этим номером
    selected_script=$(ls -1 "$SCRIPTS_DIR"/* | sed -n "${script_number}p")
    echo "$(basename "$selected_script")"
}


execScript() {
    # Получаем полный путь к скрипту, и проверяем его существование
    script_path="$SCRIPTS_DIR/$1"

    if [ ! -f "$script_path" ]; then
        echo "Скрипт $script_name не найден."
        exit 1
    fi

    # Запрос подтверждения перед выполнением
    echo "Вы уверены, что хотите запустить скрипт $script_name? (y/n)"
    read confirm
    if [ "$confirm" == "y" ]; then
        bash "$script_path"
    else
        echo "Выполнение отменено."
        exit 0
    fi
}

# Вывод синтаксиса команды при наличии аргумента --help
if [ "$1" == "--help" ]; then
    echo "Синтаксис команды:"
    echo "  Без аргументов: запуск интерактивного режима выбора скрипта из папки."
    echo "  С аргументом: запуск выполнения указанного скрипта из папки."
    exit 0
fi

# Проверка наличия аргумента
if [ $# -eq 0 ]; then

    # Если скрипт вызван без аргументов, покажем ему все скрипты
    list_scripts

    # Получаем количество скриптов в директории
    script_count=$(ls -1 "$SCRIPTS_DIR"/* | wc -l)

    # Запрашиваем у пользователя ввод номера скрипта
    echo "Введите номер скрипта (от 1 до $script_count):"
    read script_number
    
    script_name=`selectScript`
    
    # echo $script_name
    execScript $script_name

elif [ $# -eq 1 ]; then
    # Если скрипт вызван с аргументом, проверяем его существование
    script_name="$1"
    execScript $script_name

else
    echo "Неверное количество аргументов."
    exit 1
fi
