#!/usr/bin/env bash
# Check if SUPERVISOR_PHP_USER is set to either 'root' or 'sail'
if [[ "$SUPERVISOR_PHP_USER" != "root" && "$SUPERVISOR_PHP_USER" != "sail" ]]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'sail' or 'root'."
    exit 1
fi

# Update sail user ID if WWWUSER is set
if [[ -n "$WWWUSER" ]]; then
    usermod -u "$WWWUSER" sail
fi

# Create /.composer directory if it doesn't exist
mkdir -p /.composer

# Set read/write/execute permissions for all users on /.composer
chmod -R ugo+rw /.composer

# Execute the provided command or start supervisord
if [[ $# -gt 0 ]]; then
    if [[ "$SUPERVISOR_PHP_USER" == "root" ]]; then
        exec "$@"
    else
        exec gosu "$WWWUSER" bash -c "$@"
    fi
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
