services:
    web:
        build:
            context: '${PROJECT_DIR}/web-container/'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: forlaravel/1.1
        command: tail -f /dev/null
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
        volumes:
            - '${PROJECT_DIR}:/var/www/html'
        networks:
            - sail

networks:
    sail:
        driver: bridge
